In [116]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [117]:
df = pd.read_csv("cancer dataset.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [118]:
from sklearn.preprocessing import LabelEncoder

In [119]:
labelencoder_Y=LabelEncoder()
df.iloc[:,1]=labelencoder_Y.fit_transform(df.iloc[:,1].values)

In [120]:
X=df.iloc[:,2:31].values 
Y=df.iloc[:,1].values

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.25, random_state=0)

In [122]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

### Logistic Regression

In [123]:
def logreg (X_train, Y_train):
    from sklearn.linear_model import LogisticRegression
    log=LogisticRegression (random_state=0)
    log.fit(X_train, Y_train)
    print("Logistic Regression Training Accuracy:", log.score(X_train, Y_train))
    return log

In [124]:
logrex=logreg(X_train, Y_train)

Logistic Regression Training Accuracy: 0.9906103286384976


C:\Users\venkatesh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [125]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, logrex.predict(X_test))
print(cm)

[[86  4]
 [ 3 50]]


In [142]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test,logrex.predict(X_test)))
print("Accuracy:",accuracy_score(Y_test,logrex.predict(X_test)))

              precision    recall  f1-score   support

           0       0.97      0.96      0.96        90
           1       0.93      0.94      0.93        53

    accuracy                           0.95       143
   macro avg       0.95      0.95      0.95       143
weighted avg       0.95      0.95      0.95       143

Accuracy: 0.951048951048951


In [127]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of logistic regression model=", (TP+TN)/(TP+TN+FN+FP))
print("Misclassification rate of logistic regression model=",(FP+FN)/(TP+TN+FN+FP))

Testing accuracy of logistic regression model= 0.951048951048951
Misclassification rate of logistic regression model= 0.04895104895104895


### Decision Tree

In [128]:
def decisiontree(X_train,Y_train):
    from sklearn.tree import DecisionTreeClassifier
    tree = DecisionTreeClassifier(random_state=0,criterion='entropy')
    tree.fit(X_train,Y_train)
    print(tree.score(X_train,Y_train))
    return tree

In [129]:
decision = decisiontree(X_train,Y_train) 

1.0


In [130]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, decision.predict(X_test))
print(cm)

[[83  7]
 [ 2 51]]


In [141]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test,decision.predict(X_test)))
print("Accuracy:",accuracy_score(Y_test,decision.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      0.92      0.95        90
           1       0.88      0.96      0.92        53

    accuracy                           0.94       143
   macro avg       0.93      0.94      0.93       143
weighted avg       0.94      0.94      0.94       143

Accuracy: 0.9370629370629371


In [132]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of decision tree model=", (TP+TN)/(TP+TN+FN+FP))
print("Misclassification rate of decision tree model=",(FP+FN)/(TP+TN+FN+FP))

Testing accuracy of decision tree model= 0.9370629370629371
Misclassification rate of decision tree model= 0.06293706293706294


### Random Forest

In [133]:
def randomfor(X_train,Y_train):
    from sklearn.ensemble import RandomForestClassifier
    clf = RandomForestClassifier(random_state=0)
    clf.fit(X_train,Y_train)
    print(clf.score(X_train,Y_train))
    return clf

In [134]:
random = randomfor(X_train,Y_train)

0.9976525821596244


C:\Users\venkatesh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [135]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, random.predict(X_test))
print(cm)

[[85  5]
 [ 1 52]]


In [143]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test,random.predict(X_test)))
print("Accuracy:",accuracy_score(Y_test,random.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.94      0.97        90
           1       0.91      0.98      0.95        53

    accuracy                           0.96       143
   macro avg       0.95      0.96      0.96       143
weighted avg       0.96      0.96      0.96       143

Accuracy: 0.958041958041958


In [137]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of randomforestclassifier model=", (TP+TN)/(TP+TN+FN+FP))
print("Misclassification rate of random forest classifier model=",(FP+FN)/(TP+TN+FN+FP))

Testing accuracy of randomforestclassifier model= 0.958041958041958
Misclassification rate of random forest classifier model= 0.04195804195804196


Random forest classifier given highest accuracy this is beacause the decision tree model gives high importance to a particular set of features but the random forest chooses features randomly during the training process. This randomized feature selection makes random forest much more accurate than a decision tree.